// Complete patterns database with all 150 patterns
const patterns = [
  // BASIC STAR PATTERNS
  { 
    id: 1, 
    name: "Square Pattern (Solid)", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "A solid square filled with stars", 
    preview: ["****", "****", "****", "****"], 
    rows: 4, 
    popularity: 95, 
    completionRate: 92,
    formula: "stars = n, spaces = 0",
    loops: 2,
    conditions: 0
  },
  { 
    id: 2, 
    name: "Right Triangle Pattern", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Stars forming a right triangle", 
    preview: ["*", "**", "***", "****"], 
    rows: 4, 
    popularity: 98, 
    completionRate: 95,
    formula: "stars = i, spaces = 0",
    loops: 2,
    conditions: 0
  },
  { 
    id: 3, 
    name: "Left Triangle Pattern", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Stars aligned to the left forming triangle", 
    preview: ["   *", "  **", " ***", "****"], 
    rows: 4, 
    popularity: 87, 
    completionRate: 89,
    formula: "stars = i, spaces = n-i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 4, 
    name: "Inverted Right Triangle", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Upside-down right triangle", 
    preview: ["****", "***", "**", "*"], 
    rows: 4, 
    popularity: 85, 
    completionRate: 88,
    formula: "stars = n-i+1, spaces = 0",
    loops: 2,
    conditions: 0
  },
  { 
    id: 5, 
    name: "Inverted Left Triangle", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Upside-down left-aligned triangle", 
    preview: ["****", " ***", "  **", "   *"], 
    rows: 4, 
    popularity: 82, 
    completionRate: 85,
    formula: "stars = n-i+1, spaces = i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 6, 
    name: "Isosceles Triangle", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Centered triangle with equal sides", 
    preview: ["  *  ", " *** ", "*****"], 
    rows: 3, 
    popularity: 91, 
    completionRate: 90,
    formula: "stars = 2*i+1, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 7, 
    name: "Inverted Isosceles Triangle", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Upside-down centered triangle", 
    preview: ["*****", " *** ", "  *  "], 
    rows: 3, 
    popularity: 88, 
    completionRate: 86,
    formula: "stars = 2*(n-i-1)+1, spaces = i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 8, 
    name: "Rectangle Pattern", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Solid rectangle with different width and height", 
    preview: ["******", "******", "******", "******"], 
    rows: 4, 
    popularity: 89, 
    completionRate: 91,
    formula: "stars = width, spaces = 0",
    loops: 2,
    conditions: 0
  },
  { 
    id: 9, 
    name: "Parallelogram Pattern", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "Slanted rectangle pattern", 
    preview: ["    ****", "   ****", "  ****", " ****"], 
    rows: 4, 
    popularity: 76, 
    completionRate: 78,
    formula: "stars = width, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 10, 
    name: "Right Angle Pattern", 
    category: "basic-star", 
    difficulty: "easy", 
    description: "L-shaped pattern", 
    preview: ["*", "**", "***", "****", "*****"], 
    rows: 5, 
    popularity: 84, 
    completionRate: 87,
    formula: "stars = i+1, spaces = 0",
    loops: 2,
    conditions: 0
  },

  // HOLLOW PATTERNS
  { 
    id: 11, 
    name: "Hollow Square", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Square with hollow interior", 
    preview: ["****", "*  *", "*  *", "****"], 
    rows: 4, 
    popularity: 84, 
    completionRate: 76,
    formula: "stars = n (if first/last row/col), spaces = n-2 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 12, 
    name: "Hollow Rectangle", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Rectangle with empty center", 
    preview: ["******", "*    *", "*    *", "******"], 
    rows: 4, 
    popularity: 81, 
    completionRate: 74,
    formula: "stars = width (if first/last row/col), spaces = width-2 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 13, 
    name: "Hollow Right Triangle", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Right triangle with hollow center", 
    preview: ["*", "**", "* *", "****"], 
    rows: 4, 
    popularity: 78, 
    completionRate: 71,
    formula: "stars = i (if first/last col), spaces = i-2 (middle)",
    loops: 2,
    conditions: 3
  },
  { 
    id: 14, 
    name: "Hollow Left Triangle", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Left-aligned triangle with hollow center", 
    preview: ["   *", "  **", " * *", "****"], 
    rows: 4, 
    popularity: 75, 
    completionRate: 68,
    formula: "stars = i (if first/last col), spaces = n-i-1 + i-2 (middle)",
    loops: 2,
    conditions: 3
  },
  { 
    id: 15, 
    name: "Hollow Isosceles Triangle", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Centered triangle with hollow center", 
    preview: ["  *  ", " * * ", "*   *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 82, 
    completionRate: 73,
    formula: "stars = 1 (if first/last), spaces = n-i-1 + i-1 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 16, 
    name: "Hollow Diamond", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Diamond with hollow center", 
    preview: ["  *  ", " * * ", "*   *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 85, 
    completionRate: 76,
    formula: "stars = 1 (if first/last), spaces = n-i-1 + i-1 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 17, 
    name: "Hollow Rhombus", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Rhombus shape with hollow center", 
    preview: ["    *    ", "   * *   ", "  *   *  ", " *     * ", "*       *", " *     * ", "  *   *  ", "   * *   ", "    *    "], 
    rows: 9, 
    popularity: 79, 
    completionRate: 72,
    formula: "stars = 1 (if first/last), spaces = n-i-1 + i-1 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 18, 
    name: "Hollow Circle (approximate)", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Approximate circle using characters", 
    preview: ["  ***  ", " *   * ", "*     *", "*     *", " *   * ", "  ***  "], 
    rows: 6, 
    popularity: 77, 
    completionRate: 69,
    formula: "stars = 1 (if on circle boundary), spaces = calculated",
    loops: 2,
    conditions: 6
  },
  { 
    id: 19, 
    name: "Hollow Heart Shape", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Heart shape with hollow center", 
    preview: [" *   * ", "*** ***", "*******", " ***** ", "  ***  ", "   *   "], 
    rows: 6, 
    popularity: 88, 
    completionRate: 65,
    formula: "stars = 1 (if on heart boundary), spaces = calculated",
    loops: 2,
    conditions: 8
  },
  { 
    id: 20, 
    name: "Hollow Arrow Pattern", 
    category: "hollow", 
    difficulty: "medium", 
    description: "Arrow shape with hollow center", 
    preview: ["  *  ", " *** ", "*****", "  *  ", "  *  "], 
    rows: 5, 
    popularity: 74, 
    completionRate: 67,
    formula: "stars = 1 (if on arrow boundary), spaces = calculated",
    loops: 2,
    conditions: 5
  },

  // PYRAMID PATTERNS
  { 
    id: 21, 
    name: "Full Pyramid (Star)", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Complete pyramid with centered stars", 
    preview: ["    *    ", "   ***   ", "  *****  ", " ******* ", "*********"], 
    rows: 5, 
    popularity: 93, 
    completionRate: 89,
    formula: "stars = 2*i+1, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 22, 
    name: "Inverted Full Pyramid", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Upside-down complete pyramid", 
    preview: ["*********", " ******* ", "  *****  ", "   ***   ", "    *    "], 
    rows: 5, 
    popularity: 90, 
    completionRate: 86,
    formula: "stars = 2*(n-i-1)+1, spaces = i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 23, 
    name: "Half Pyramid Left", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Left-aligned half pyramid", 
    preview: ["*", "**", "***", "****", "*****"], 
    rows: 5, 
    popularity: 95, 
    completionRate: 92,
    formula: "stars = i+1, spaces = 0",
    loops: 2,
    conditions: 0
  },
  { 
    id: 24, 
    name: "Half Pyramid Right", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Right-aligned half pyramid", 
    preview: ["    *", "   **", "  ***", " ****", "*****"], 
    rows: 5, 
    popularity: 92, 
    completionRate: 89,
    formula: "stars = i+1, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 25, 
    name: "Step Pyramid", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Pyramid with stepped levels", 
    preview: ["*", "**", "***", "****", "*****", "****", "***", "**", "*"], 
    rows: 9, 
    popularity: 87, 
    completionRate: 84,
    formula: "stars = i+1 (if i < n/2), stars = 2*n-i-1 (if i >= n/2)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 26, 
    name: "Double Pyramid", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Two pyramids side by side", 
    preview: ["*   *", "** **", "*** ***", "**** ****", "***** *****"], 
    rows: 5, 
    popularity: 85, 
    completionRate: 82,
    formula: "stars = i+1 (each pyramid), spaces = n-i-1 (between)",
    loops: 2,
    conditions: 0
  },
  { 
    id: 27, 
    name: "Truncated Pyramid", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Pyramid with flat top", 
    preview: ["*****", " **** ", "  ***  ", "   **   ", "    *    "], 
    rows: 5, 
    popularity: 83, 
    completionRate: 80,
    formula: "stars = n-i, spaces = i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 28, 
    name: "Multi-level Pyramid", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Pyramid with multiple levels", 
    preview: ["*", "**", "***", "****", "***", "**", "*", "**", "***"], 
    rows: 9, 
    popularity: 81, 
    completionRate: 78,
    formula: "stars = calculated based on level",
    loops: 2,
    conditions: 2
  },
  { 
    id: 29, 
    name: "Staircase Pattern", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Staircase-like pattern", 
    preview: ["*", "**", "***", "****", "*****", "****", "***", "**", "*"], 
    rows: 9, 
    popularity: 86, 
    completionRate: 83,
    formula: "stars = i+1 (if i < n/2), stars = 2*n-i-1 (if i >= n/2)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 30, 
    name: "Reverse Staircase", 
    category: "pyramid", 
    difficulty: "easy", 
    description: "Reversed staircase pattern", 
    preview: ["*****", "****", "***", "**", "*", "**", "***", "****", "*****"], 
    rows: 9, 
    popularity: 84, 
    completionRate: 81,
    formula: "stars = n-i (if i < n/2), stars = i+1 (if i >= n/2)",
    loops: 2,
    conditions: 1
  },

  // DIAMOND PATTERNS
  { 
    id: 31, 
    name: "Diamond Pattern (Solid)", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Solid diamond shape", 
    preview: ["  *  ", " *** ", "*****", " *** ", "  *  "], 
    rows: 5, 
    popularity: 89, 
    completionRate: 82,
    formula: "stars = 2*i+1 (upper), 2*(n-i-1)+1 (lower), spaces = n-i-1",
    loops: 2,
    conditions: 1
  },
  { 
    id: 32, 
    name: "Hollow Diamond", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond with hollow center", 
    preview: ["  *  ", " * * ", "*   *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 85, 
    completionRate: 76,
    formula: "stars = 1 (if first/last), spaces = n-i-1 + i-1 (middle)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 33, 
    name: "Double Diamond", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Two diamonds side by side", 
    preview: ["  *   *  ", " *** *** ", "***** *****", " *** *** ", "  *   *  "], 
    rows: 5, 
    popularity: 82, 
    completionRate: 74,
    formula: "stars = 2*i+1 (each diamond), spaces = n-i-1 (between)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 34, 
    name: "Diamond with Cross", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond with cross pattern inside", 
    preview: ["  *  ", " * * ", "* * *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 78, 
    completionRate: 71,
    formula: "stars = 1 (if on diamond or cross), spaces = calculated",
    loops: 2,
    conditions: 6
  },
  { 
    id: 35, 
    name: "Tilted Diamond", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond rotated 45 degrees", 
    preview: ["*", "**", "***", "**", "*"], 
    rows: 5, 
    popularity: 76, 
    completionRate: 69,
    formula: "stars = i+1 (if i < n/2), stars = 2*n-i-1 (if i >= n/2)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 36, 
    name: "Diamond Border", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond with thick border", 
    preview: ["  ***  ", " ***** ", "*******", " ***** ", "  ***  "], 
    rows: 5, 
    popularity: 74, 
    completionRate: 67,
    formula: "stars = 2*i+3 (upper), 2*(n-i-1)+3 (lower), spaces = n-i-2",
    loops: 2,
    conditions: 1
  },
  { 
    id: 37, 
    name: "Nested Diamond", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond within a diamond", 
    preview: ["  *  ", " * * ", "* * *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 72, 
    completionRate: 65,
    formula: "stars = 1 (if on outer or inner diamond), spaces = calculated",
    loops: 2,
    conditions: 8
  },
  { 
    id: 38, 
    name: "Diamond Grid", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Grid of small diamonds", 
    preview: ["* * *", " * * ", "* * *", " * * ", "* * *"], 
    rows: 5, 
    popularity: 70, 
    completionRate: 63,
    formula: "stars = 1 (if on diamond grid), spaces = 1 (between)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 39, 
    name: "Split Diamond", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Diamond split in half", 
    preview: ["  *  ", " * * ", "*   *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 68, 
    completionRate: 61,
    formula: "stars = 1 (if on diamond boundary), spaces = calculated",
    loops: 2,
    conditions: 4
  },
  { 
    id: 40, 
    name: "Diamond Lattice", 
    category: "diamond", 
    difficulty: "medium", 
    description: "Lattice pattern with diamonds", 
    preview: ["*   *", " * * ", "  *  ", " * * ", "*   *"], 
    rows: 5, 
    popularity: 66, 
    completionRate: 59,
    formula: "stars = 1 (if on lattice), spaces = calculated",
    loops: 2,
    conditions: 6
  }
];

export default patterns;


