// Remaining patterns (41-150)
const remainingPatterns = [
  // NUMBER PATTERNS
  { 
    id: 41, 
    name: "Number Triangle (1,2,3...)", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with sequential numbers", 
    preview: ["1", "12", "123", "1234"], 
    rows: 4, 
    popularity: 92, 
    completionRate: 88,
    formula: "numbers = 1 to i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 42, 
    name: "Repeated Number Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with repeated numbers", 
    preview: ["1", "22", "333", "4444"], 
    rows: 4, 
    popularity: 89, 
    completionRate: 85,
    formula: "numbers = i (repeated i times)",
    loops: 2,
    conditions: 0
  },
  { 
    id: 43, 
    name: "Floyd's Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Sequential numbers in triangular form", 
    preview: ["1", "2 3", "4 5 6", "7 8 9 10"], 
    rows: 4, 
    popularity: 84, 
    completionRate: 79,
    formula: "numbers = counter to counter+i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 44, 
    name: "Pascal's Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Mathematical triangle with binomial coefficients", 
    preview: ["1", "1 1", "1 2 1", "1 3 3 1"], 
    rows: 4, 
    popularity: 87, 
    completionRate: 82,
    formula: "numbers = binomial coefficient C(i,j)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 45, 
    name: "Number Pyramid", 
    category: "number", 
    difficulty: "medium", 
    description: "Numbers arranged in pyramid form", 
    preview: ["  1  ", " 123 ", "12345"], 
    rows: 3, 
    popularity: 85, 
    completionRate: 80,
    formula: "numbers = 1 to 2*i+1, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 46, 
    name: "Reverse Number Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with numbers in reverse order", 
    preview: ["4321", "321", "21", "1"], 
    rows: 4, 
    popularity: 83, 
    completionRate: 78,
    formula: "numbers = i to 1 (reverse)",
    loops: 2,
    conditions: 0
  },
  { 
    id: 47, 
    name: "Binary Triangle (0,1)", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with binary numbers", 
    preview: ["1", "01", "101", "0101"], 
    rows: 4, 
    popularity: 81, 
    completionRate: 76,
    formula: "numbers = (i+j) % 2",
    loops: 2,
    conditions: 1
  },
  { 
    id: 48, 
    name: "Fibonacci Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with Fibonacci numbers", 
    preview: ["1", "1 1", "1 1 2", "1 1 2 3"], 
    rows: 4, 
    popularity: 79, 
    completionRate: 74,
    formula: "numbers = Fibonacci sequence",
    loops: 2,
    conditions: 1
  },
  { 
    id: 49, 
    name: "Prime Number Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle with prime numbers", 
    preview: ["2", "3 5", "7 11 13", "17 19 23 29"], 
    rows: 4, 
    popularity: 77, 
    completionRate: 72,
    formula: "numbers = prime sequence",
    loops: 2,
    conditions: 2
  },
  { 
    id: 50, 
    name: "Even-Odd Triangle", 
    category: "number", 
    difficulty: "medium", 
    description: "Triangle alternating even and odd numbers", 
    preview: ["1", "2 3", "4 5 6", "7 8 9 10"], 
    rows: 4, 
    popularity: 75, 
    completionRate: 70,
    formula: "numbers = sequential with even/odd pattern",
    loops: 2,
    conditions: 1
  },
  { 
    id: 51, 
    name: "Number Diamond", 
    category: "number", 
    difficulty: "medium", 
    description: "Numbers arranged in diamond form", 
    preview: ["  1  ", " 123 ", "12345", " 123 ", "  1  "], 
    rows: 5, 
    popularity: 73, 
    completionRate: 68,
    formula: "numbers = 1 to 2*i+1 (upper), 1 to 2*(n-i-1)+1 (lower)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 52, 
    name: "Number Square Pattern", 
    category: "number", 
    difficulty: "medium", 
    description: "Numbers in square formation", 
    preview: ["1234", "5678", "9012", "3456"], 
    rows: 4, 
    popularity: 71, 
    completionRate: 66,
    formula: "numbers = counter++",
    loops: 2,
    conditions: 0
  },
  { 
    id: 53, 
    name: "Multiplication Table Pattern", 
    category: "number", 
    difficulty: "medium", 
    description: "Multiplication table in pattern form", 
    preview: ["1 2 3 4", "2 4 6 8", "3 6 9 12", "4 8 12 16"], 
    rows: 4, 
    popularity: 69, 
    completionRate: 64,
    formula: "numbers = i * j",
    loops: 2,
    conditions: 0
  },
  { 
    id: 54, 
    name: "Sequential Number Pattern", 
    category: "number", 
    difficulty: "medium", 
    description: "Sequential numbers in various arrangements", 
    preview: ["1", "2 3", "4 5 6", "7 8 9 10"], 
    rows: 4, 
    popularity: 67, 
    completionRate: 62,
    formula: "numbers = counter++",
    loops: 2,
    conditions: 0
  },
  { 
    id: 55, 
    name: "Palindrome Number Pattern", 
    category: "number", 
    difficulty: "medium", 
    description: "Numbers forming palindrome patterns", 
    preview: ["1", "121", "12321", "1234321"], 
    rows: 4, 
    popularity: 65, 
    completionRate: 60,
    formula: "numbers = palindrome sequence",
    loops: 2,
    conditions: 1
  },

  // ALPHABET PATTERNS
  { 
    id: 56, 
    name: "Alphabet Triangle (A,B,C...)", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Triangle with sequential alphabets", 
    preview: ["A", "AB", "ABC", "ABCD"], 
    rows: 4, 
    popularity: 94, 
    completionRate: 91,
    formula: "letters = A to A+i",
    loops: 2,
    conditions: 0
  },
  { 
    id: 57, 
    name: "Reverse Alphabet Triangle", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Triangle with reverse alphabet order", 
    preview: ["DCBA", "CBA", "BA", "A"], 
    rows: 4, 
    popularity: 91, 
    completionRate: 88,
    formula: "letters = A+i to A (reverse)",
    loops: 2,
    conditions: 0
  },
  { 
    id: 58, 
    name: "Alphabet Diamond", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets arranged in diamond form", 
    preview: ["  A  ", " ABC ", "ABCDE", " ABC ", "  A  "], 
    rows: 5, 
    popularity: 89, 
    completionRate: 86,
    formula: "letters = A to A+2*i (upper), A to A+2*(n-i-1) (lower)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 59, 
    name: "Alphabet Pyramid", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets in pyramid formation", 
    preview: ["   A   ", "  ABC  ", " ABCDE ", "ABCDEFG"], 
    rows: 4, 
    popularity: 87, 
    completionRate: 84,
    formula: "letters = A to A+2*i, spaces = n-i-1",
    loops: 2,
    conditions: 0
  },
  { 
    id: 60, 
    name: "Repeating Alphabet Pattern", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets with repetition", 
    preview: ["A", "BB", "CCC", "DDDD"], 
    rows: 4, 
    popularity: 85, 
    completionRate: 82,
    formula: "letters = A+i (repeated i+1 times)",
    loops: 2,
    conditions: 0
  },
  { 
    id: 61, 
    name: "Alphabet Square", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets in square formation", 
    preview: ["ABCD", "EFGH", "IJKL", "MNOP"], 
    rows: 4, 
    popularity: 83, 
    completionRate: 80,
    formula: "letters = A + counter++",
    loops: 2,
    conditions: 0
  },
  { 
    id: 62, 
    name: "Vowel Pattern", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Pattern using only vowels", 
    preview: ["A", "AE", "AEI", "AEIO"], 
    rows: 4, 
    popularity: 81, 
    completionRate: 78,
    formula: "letters = vowels only",
    loops: 2,
    conditions: 1
  },
  { 
    id: 63, 
    name: "Consonant Pattern", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Pattern using only consonants", 
    preview: ["B", "BC", "BCD", "BCDF"], 
    rows: 4, 
    popularity: 79, 
    completionRate: 76,
    formula: "letters = consonants only",
    loops: 2,
    conditions: 1
  },
  { 
    id: 64, 
    name: "Alphabet Wave", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets in wave pattern", 
    preview: ["A", "BC", "DEF", "GHIJ"], 
    rows: 4, 
    popularity: 77, 
    completionRate: 74,
    formula: "letters = sequential with wave spacing",
    loops: 2,
    conditions: 1
  },
  { 
    id: 65, 
    name: "Cross Alphabet Pattern", 
    category: "alphabet", 
    difficulty: "easy", 
    description: "Alphabets forming cross pattern", 
    preview: ["A   A", " B B ", "  C  ", " D D ", "E   E"], 
    rows: 5, 
    popularity: 75, 
    completionRate: 72,
    formula: "letters = A+i (if on cross), spaces = calculated",
    loops: 2,
    conditions: 2
  },

  // SPECIAL COMPLEX PATTERNS
  { 
    id: 66, 
    name: "Butterfly Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Butterfly wing pattern", 
    preview: ["*    *", "**  **", "******", "**  **", "*    *"], 
    rows: 5, 
    popularity: 91, 
    completionRate: 67,
    formula: "stars = i+1 (left), 2*(n-i-1) (right), spaces = 2*(n-i-1)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 67, 
    name: "Hourglass Pattern (Sandglass)", 
    category: "special", 
    difficulty: "hard", 
    description: "Hourglass or sandglass shape", 
    preview: ["*****", " *** ", "  *  ", " *** ", "*****"], 
    rows: 5, 
    popularity: 89, 
    completionRate: 65,
    formula: "stars = 2*(n-i-1)+1 (upper), 2*i+1 (lower), spaces = i",
    loops: 2,
    conditions: 1
  },
  { 
    id: 68, 
    name: "Bow-tie Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Bow-tie or butterfly shape", 
    preview: ["*   *", "** **", "*****", "** **", "*   *"], 
    rows: 5, 
    popularity: 87, 
    completionRate: 63,
    formula: "stars = i+1 (left), 2*(n-i-1) (right), spaces = 2*(n-i-1)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 69, 
    name: "X Pattern (Cross)", 
    category: "special", 
    difficulty: "hard", 
    description: "X or cross pattern", 
    preview: ["*   *", " * * ", "  *  ", " * * ", "*   *"], 
    rows: 5, 
    popularity: 86, 
    completionRate: 78,
    formula: "stars = 1 (if i==j or i+j==n-1)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 70, 
    name: "Plus Pattern (+)", 
    category: "special", 
    difficulty: "hard", 
    description: "Plus sign pattern", 
    preview: ["  *  ", "  *  ", "*****", "  *  ", "  *  "], 
    rows: 5, 
    popularity: 84, 
    completionRate: 76,
    formula: "stars = 1 (if i==n/2 or j==n/2)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 71, 
    name: "Minus Pattern (-)", 
    category: "special", 
    difficulty: "hard", 
    description: "Minus sign pattern", 
    preview: ["     ", "     ", "*****", "     ", "     "], 
    rows: 5, 
    popularity: 82, 
    completionRate: 74,
    formula: "stars = 1 (if i==n/2)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 72, 
    name: "Multiplication Pattern (×)", 
    category: "special", 
    difficulty: "hard", 
    description: "Multiplication sign pattern", 
    preview: ["*   *", " * * ", "  *  ", " * * ", "*   *"], 
    rows: 5, 
    popularity: 80, 
    completionRate: 72,
    formula: "stars = 1 (if i==j or i+j==n-1)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 73, 
    name: "Division Pattern (÷)", 
    category: "special", 
    difficulty: "hard", 
    description: "Division sign pattern", 
    preview: ["  *  ", "  *  ", "*****", "  *  ", "  *  "], 
    rows: 5, 
    popularity: 78, 
    completionRate: 70,
    formula: "stars = 1 (if i==n/2 or j==n/2)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 74, 
    name: "Hash Pattern (#)", 
    category: "special", 
    difficulty: "hard", 
    description: "Hash or pound sign pattern", 
    preview: ["* * *", " *** ", "*****", " *** ", "* * *"], 
    rows: 5, 
    popularity: 76, 
    completionRate: 68,
    formula: "stars = 1 (if i%2==0 or j%2==0)",
    loops: 2,
    conditions: 2
  },
  { 
    id: 75, 
    name: "Arrow Patterns (↑↓←→)", 
    category: "special", 
    difficulty: "hard", 
    description: "Arrow patterns in different directions", 
    preview: ["  *  ", " *** ", "*****", "  *  ", "  *  "], 
    rows: 5, 
    popularity: 74, 
    completionRate: 66,
    formula: "stars = 1 (if on arrow path)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 76, 
    name: "Zigzag Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Zigzag line pattern", 
    preview: ["*   *", " * * ", "  *  ", " * * ", "*   *"], 
    rows: 5, 
    popularity: 72, 
    completionRate: 64,
    formula: "stars = 1 (if on zigzag path)",
    loops: 2,
    conditions: 3
  },
  { 
    id: 77, 
    name: "Wave Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Wave-like pattern", 
    preview: ["  *  ", " * * ", "*   *", " * * ", "  *  "], 
    rows: 5, 
    popularity: 70, 
    completionRate: 62,
    formula: "stars = 1 (if on wave path)",
    loops: 2,
    conditions: 3
  },
  { 
    id: 78, 
    name: "Spiral Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Spiral pattern", 
    preview: ["*****", "*   *", "* * *", "*   *", "*****"], 
    rows: 5, 
    popularity: 68, 
    completionRate: 60,
    formula: "stars = 1 (if on spiral path)",
    loops: 2,
    conditions: 4
  },
  { 
    id: 79, 
    name: "Checkerboard Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Checkerboard or chess pattern", 
    preview: ["* * *", " * * ", "* * *", " * * ", "* * *"], 
    rows: 5, 
    popularity: 66, 
    completionRate: 58,
    formula: "stars = 1 (if (i+j)%2==0)",
    loops: 2,
    conditions: 1
  },
  { 
    id: 80, 
    name: "Maze Pattern", 
    category: "special", 
    difficulty: "hard", 
    description: "Maze-like pattern", 
    preview: ["*****", "*   *", "* * *", "*   *", "*****"], 
    rows: 5, 
    popularity: 64, 
    completionRate: 56,
    formula: "stars = 1 (if on maze wall)",
    loops: 2,
    conditions: 4
  }
];

export default remainingPatterns;


